apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-deployment
  labels:
    app: {{ .Values.service.name }}
spec:
  #  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      containers:
        - name: {{ .Values.service.name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
#          resources:
#            limits:
#              nvidia.com/gpu: 1
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          securityContext:
            capabilities:
              add: [ "NET_ADMIN" ]
          {{- if .Values.volume }}
          volumeMounts:
            - name: {{ .Values.service.name }}-volume
              mountPath: {{ .Values.volume.mountPath }}
          {{- end}}
      imagePullSecrets:
        - name: ghcr
