apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.service.name }}-ingress
  annotations:
    {{- if .Values.service.auth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- end}}
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - {{ .Values.service.host }}
      secretName: {{ .Values.service.host }}-tls-secret
  ingressClassName: nginx
  rules:
    - host: {{ .Values.service.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.service.name }}-service
                port:
                  number: 80
            path: {{ .Values.service.path }}
            pathType: Prefix
