{{- if .Values.service.getCert }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.service.host }}-letsencrypt-cert
spec:
  secretName: {{ .Values.service.host }}-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: {{ .Values.service.host }}
  dnsNames:
    - {{ .Values.service.host }}
{{- end}}
