apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.service.name }}
  ports:
    - protocol: TCP
      port:  {{ .Values.service.port }}
      targetPort:  {{ .Values.service.containerPort }}
