name: Build app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.IMAGE_NAME }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
#          tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}:latest

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          exec: helm upgrade --install cornvert.org .helm/ --set-string timestamp=${{ steps.date.outputs.date }}

